version: '3'

services:
  hugo:
    image: jojomi/hugo:latest
    restart: always
    volumes:
      - ./src/:/src
      - ./output/:/output
    environment:
      - HUGO_REFRESH_TIME=3600
      #- HUGO_THEME=simple-a
      #- HUGO_BASEURL=rustedbits.com

  web:
    image: nginx-static-ssl:latest 
    restart: always
    volumes:
      - ./output:/var/www
    environment:
      - VIRTUAL_HOST=rustedbits.com
      - LETSENCRYPT_HOST=rustedbits.com
      - LETSENCRYPT_EMAIL=connor.willhelm@gmail.com
    depends_on:
      - hugo
    networks:
      - proxy-tier
      - default

  proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock
      - vhost.d:/etc/nginx/vhost.d:ro
      - html:/usr/share/nginx/html
    networks:
    - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - proxy
    networks:
      - proxy-tier

volumes:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
